"use client";
import localFont from "@next/font/local";
import "./globals.css";
import "../style/reset.css";
import "../style/variables.css";
import { React, useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
const gdsherpa = localFont({
  src: [
    {
      path: "../public/gdsherpamedium.ttf",
      weight: "400",
    },
    {
      path: "../public/gdsherpa.ttf",
      weight: "600",
    },
    {
      path: "../public/Sherpa-BoldWeb.ttf",
      weight: "600",
    },
  ],
  variable: "--font-gdsherpa",
});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({
      duration: 800,
      once: false,
    });
  }, []);
  return (
    <html lang="en">
      <body className={`${gdsherpa.variable} font-sans`}>
        <div className="px-[10px]">
          <Navbar />

          <main>{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
