import localFont from "@next/font/local";
import "./globals.css";

import Navbar from "@/components/navbar/Navbar";
const gdsherpa = localFont({
  src: [
    {
      path: "../public/gdsherpamedium.ttf",
      weight: "400",
    },
    {
      path: "../public/gdsherpa.ttf",
      weight: "600",
    },
    {
      path: "../public/Sherpa-BoldWeb.ttf",
      weight: "600",
    },
  ],
  variable: "--font-gdsherpa",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gdsherpa.variable} font-sans`}>
        <div className="px-[10px]">
          <Navbar />
          <main className="bg-[#F5F7F8]">{children}</main>
        </div>
      </body>
    </html>
  );
}
